<font color='darkred'> Unless otherwise noted, **this notebook will not be reviewed or autograded.**</font> You are welcome to use it for scratchwork, but **only the files listed in the exercises will be checked.**

---

# Exercises

For these exercises, add your functions to the *apputil\.py* file. If you like, you're welcome to adjust the *app\.py* file, but it is not required.

## Notes on Recursion

A [recursive function](https://www.w3schools.com/python/gloss_python_function_recursion.asp) is one which calls itself.

1. When the function is called, your CPU runs through each line of code until the function needs to be called again.
2. At that point, all variables are saved in memory, and the function runs through each line of code again until the function is called (again, but with a different passed argument), and so on.
3. Eventually, this process will stop at the "bottom of the **stack**", where the function doesn't get a chance to call itself again (likely because of some condition un/met by the latest passed argument).
4. Then, your CPU will work its way back up the stack to the final result. For example, take a look at [this visual example](https://realpython.com/python-recursion/#calculate-factorial) of calculating 4!.

When you write these functions, keep two things in mind:

- You will need a built-in stopping point (i.e., the "bottom"), where your function returns some result before it calls itself.
- **Don't think too hard about this.** Recursion can be perplexing to conceptualize when writing the code. So, when you call the function inside the function, think about it as a magical "hidden" function that has already done what you want it to do.
- [Python Tutor](https://pythontutor.com/) ([editor](https://pythontutor.com/visualize.html#mode=edit)) can be a helpful resource for this exercise!

## Exercise 1

The Fibonacci Series is credited to Leonardo Bonacci (_**fi**lius Bonacci_, 'son of Bonacci'), but can be traced back to early Indian mathematicians (circa 400BC). Starting with $\{0, \ 1\}$, each of the following numbers are the sum of the previous two numbers in the series.

`0 1 1 2 3 5 8 13 21 34 ...`

So, `fibonacci(9) = 34`. *Note: If the sequence starts with $\{2,\ 1\}$, it is then the [Lucas Sequence](https://en.wikipedia.org/wiki/Lucas_number).*

Write a recursive function (`fibonacci`) that, given `n`, will return the `n`th number of the Fibonacci Series.

*Test your function using Google or any other tool that can calculate the Fibonacci Series.*

In [17]:
def fibonacci(n):
    '''
    Given n, this function will return the nth number of the Fibonacci Series.
    '''
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n-2) + fibonacci(n-1)

fibonacci(20)

6765


## Exercise 2

Write a (single) recursive function, `to_binary()`, that [converts](https://en.wikipedia.org/wiki/Binary_number#Conversion_to_and_from_other_numeral_systems) an integer into its [binary](https://en.wikipedia.org/wiki/Binary_number) representation. So, for example:

```python
to_binary(2)   -->  10
to_binary(12)  -->  1100
```

*Note: you can test your function with the built in `bin()` function.*

In [ ]:
def to_binary(i):
    '''
    Given an integer, this function will return its binary representation.
    '''
    if i == 0:
        return 0
    elif i == 1:
        return 1
    else:
        return int(str(to_binary(i // 2)) + str(i%2))

to_binary(8)

8
4
2

1000

In [9]:
bin(8)

'0b1000'

## Exercise 3 

Use the raw Bellevue Almshouse Dataset (`df_bellevue`) extracted at the top of the lab (i.e., with `pd.read_csv ...`).

**Write a function for each of the following tasks. Name these functions `task_i()`** (i.e., without any input arguments).

1. Return a list of all column names, *sorted* such that the first column has the *least* missing values, and the last column has the *most* missing values (use the raw column names).
   - *Note: there is an issue with the `gender` column you'll need to remedy first ...*
2. Return a **data frame** with two columns:
   - the year (for each year in the data), `year`
   - the total number of entries (immigrant admissions) for each year, `total_admissions`
3. Return a **series** with:
   - Index: gender (for each gender in the data)
   - Values: the average age for the indexed gender.
4. Return a list of the 5 most common professions *in order of prevalence* (so, the most common is first).

For each of these, if there are messy data issues, use the `print` statement to explain.

In [8]:
import pandas as pd
import numpy as np

url = 'https://github.com/melaniewalsh/Intro-Cultural-Analytics/raw/master/book/data/bellevue_almshouse_modified.csv'

df_bellevue = pd.read_csv(url)

In [ ]:
def task_1():
    '''
    Returns a list of all column names, sorted in order from least missing
    values to most missing values.
    '''
    bellevue_cols = []

    #replace '?', 'h', 'g' genders with NaN
    df_bellevue.loc[:, ['gender']] = df_bellevue['gender'].replace(['?', 'h', 'g'], np.nan)

    for col in df_bellevue:
        bellevue_cols.append((col, df_bellevue[col].isna().sum()))
    bellevue_cols.sort(key=lambda x: x[1])
    print(bellevue_cols)
    bellevue_cols_sorted = [col[0] for col in bellevue_cols]
    return bellevue_cols_sorted

task_1()

[('date_in', np.int64(0)), ('last_name', np.int64(0)), ('first_name', np.int64(4)), ('gender', np.int64(5)), ('age', np.int64(50)), ('profession', np.int64(1019)), ('disease', np.int64(3087)), ('children', np.int64(9547))]

['date_in',
 'last_name',
 'first_name',
 'gender',
 'age',
 'profession',
 'disease',
 'children']

In [3]:
df_bellevue.head()

,date_in,first_name,last_name,age,disease,profession,gender,children
0,1847-04-17,Mary,Gallagher,28.0,recent emigrant,married,w,Child Alana 10 days
1,1847-04-08,John,Sanin (?),19.0,recent emigrant,laborer,m,Catherine 2 mo
2,1847-04-17,Anthony,Clark,60.0,recent emigrant,laborer,m,Charles Riley afed 10 days
3,1847-04-08,Lawrence,Feeney,32.0,recent emigrant,laborer,m,Child
4,1847-04-13,Henry,Joyce,21.0,recent emigrant,NaN,m,Child 1 mo

In [ ]:
def task_2():
    df_bellevue['year'] = pd.to_datetime(df_bellevue['date_in']).dt.year
    df_year_admins = df_bellevue.groupby('year') \
                                .size() \
                                .reset_index(name='total_admissions') \
                                .sort_values('year') \
                                .reset_index(drop=True)
    return df_year_admins[['year', 'total_admissions']]

task_2()

<bound method DataFrame.info of    year  total_admissions
0  1846              3073
1  1847              6511>

In [84]:
def task_2():
    '''
    Returns a data frame with two columns ('year' and 'total_admissions'), describing
    the amount of admissions for each year in the dataset.
    '''
    df_bellevue['year'] = pd.to_datetime(df_bellevue['date_in']).dt.year
    df_year_admins = df_bellevue['year'].value_counts() \
                                        .reset_index(name='total_admissions') \
                                        .sort_values('year') \
                                        .reset_index(drop=True)
    return df_year_admins[['year', 'total_admissions']]

task_2()

   year  total_admissions
0  1846              3073
1  1847              6511

In [58]:
def task_3():
    '''
    Returns a series with 'gender' as the index, and the average age for each gender
    as the value.
    '''
    df_gender_mean_age = df_bellevue.groupby('gender') \
                                    [['age']].mean()
    return df_gender_mean_age['age'].info

task_3()

<bound method Series.info of gender
m    31.813433
w    28.725162
Name: age, dtype: float64>

## (Optional) Bonus Exercise 4

[Memoization](https://en.wikipedia.org/wiki/Memoization) is a technique where you store the results of expensive function calls and return the cached result when the same inputs occur again. This is a form of dynamic programming, and we can apply it to either of the above recursive functions to improve efficiency.

Write a memoized version of either the `fibonacci` or `to_binary` function above. *Hint: consider using a `global`ly defined `defaultdict`.*